name: Deploy App to EC2 with Docker Compose

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted # Đã cài runner trên EC2

    steps:
      - name: Pull latest code
        run: |
          cd /home/ubuntu/deploy-to-ec2-by-github-ci-cd
          git reset --hard
          git pull origin main

      - name: Rebuild and restart with Docker Compose
        run: |
          cd /home/ubuntu/deploy-to-ec2-by-github-ci-cd
          docker compose down
          docker compose up --build -d
